// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARoIUpjYQHqSlGOFXaNecrdAW1VAJAvf4',
    appId: '1:1178937216:web:ad15127072860897b30365',
    messagingSenderId: '1178937216',
    projectId: 'my-book-app-84a43',
    authDomain: 'my-book-app-84a43.firebaseapp.com',
    storageBucket: 'my-book-app-84a43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3d2ejQt6Yj8Gj7ApTZt4g2d5VPGc6OKg',
    appId: '1:1178937216:android:d6a8d27dbf235078b30365',
    messagingSenderId: '1178937216',
    projectId: 'my-book-app-84a43',
    storageBucket: 'my-book-app-84a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_sc-elOnemYMwkCGADlRaujDymlQqHww',
    appId: '1:1178937216:ios:4893d1d7bd3cc5a4b30365',
    messagingSenderId: '1178937216',
    projectId: 'my-book-app-84a43',
    storageBucket: 'my-book-app-84a43.appspot.com',
    iosClientId: '1178937216-cd6d04e9jfnc2816q8e4mi0396va5jp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hbProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_sc-elOnemYMwkCGADlRaujDymlQqHww',
    appId: '1:1178937216:ios:4893d1d7bd3cc5a4b30365',
    messagingSenderId: '1178937216',
    projectId: 'my-book-app-84a43',
    storageBucket: 'my-book-app-84a43.appspot.com',
    iosClientId: '1178937216-cd6d04e9jfnc2816q8e4mi0396va5jp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hbProject1',
  );
}
